# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: dco

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - uses: tim-actions/dco@master
